[build]
  # This command is run when you deploy the site.
  # It installs all dependencies listed in package.json.
  command = "npm install"
  # This is the directory where our serverless functions are located.
  functions = "netlify/functions"

# This is a redirect rule that makes our API cleaner to call,
# but we are calling the direct URL in js/main.js for simplicity.
# You could use this in the future if you want.
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200 